x-common-environment: &kafka_broker_common_env_vars # KRaft settings
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:19091,2@kafka-2:19091,3@kafka-3:19091"
  # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid"
  # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
  CLUSTER_ID: ${KAFKA_CLUSTER_ID:-42RglGpZQwy9D5VzTVpCWA}
  # Common Kafka settings
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT,LISTENER_MINIKUBE:PLAINTEXT
  KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
  KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
  KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
  KAFKA_NUM_PARTITIONS: "3"
  KAFKA_DEFAULT_REPLICATION_FACTOR: "3"
  KAFKA_LOG_CLEANUP_POLICY: "delete"
  KAFKA_LOG_RETENTION_BYTES: "524288000" # 500 MB
  KAFKA_LOG_SEGMENT_BYTES: "67108864" # 64 MB segments
  KAFKA_LOG_RETENTION_MS: "86400000" # 1 day

services:
  kpow:
    image: factorhouse/kpow:latest
    container_name: kpow
    pull_policy: always
    restart: always
    ports:
      - "3000:3000"
      - "4000:4000"
    networks:
      - factorhouse
    env_file:
      - ./config/setup.env
      - ${KPOW_LICENSE:-./config/license.env}
    mem_limit: 2G
    volumes:
      - ./jaas:/etc/kpow/jaas
      - ./rbac:/etc/kpow/rbac

  kafka-1:
    image: confluentinc/cp-kafka:8.1.1
    container_name: kafka-1
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - factorhouse
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: CONTROLLER://kafka-1:19091,LISTENER_DOCKER_INTERNAL://kafka-1:19092,LISTENER_DOCKER_EXTERNAL://0.0.0.0:9092,LISTENER_MINIKUBE://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka-1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,LISTENER_MINIKUBE://host.minikube.internal:29092
      <<: *kafka_broker_common_env_vars

  kafka-2:
    image: confluentinc/cp-kafka:8.1.1
    container_name: kafka-2
    ports:
      - "9093:9093"
      - "29093:29093"
    networks:
      - factorhouse
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: CONTROLLER://kafka-2:19091,LISTENER_DOCKER_INTERNAL://kafka-2:19093,LISTENER_DOCKER_EXTERNAL://0.0.0.0:9093,LISTENER_MINIKUBE://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka-2:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093,LISTENER_MINIKUBE://host.minikube.internal:29093
      <<: *kafka_broker_common_env_vars

  kafka-3:
    image: confluentinc/cp-kafka:8.1.1
    container_name: kafka-3
    ports:
      - "9094:9094"
      - "29094:29094"
    networks:
      - factorhouse
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: CONTROLLER://kafka-3:19091,LISTENER_DOCKER_INTERNAL://kafka-3:19094,LISTENER_DOCKER_EXTERNAL://0.0.0.0:9094,LISTENER_MINIKUBE://0.0.0.0:29094
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka-3:19094,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094,LISTENER_MINIKUBE://host.minikube.internal:29094
      <<: *kafka_broker_common_env_vars

networks:
  factorhouse:
    name: factorhouse
